### ISSUE TITLE
Type conversion and truncation errors

### ISSUE THREAD

**Issue by maltezfaria** [WaveProp/PolynomialSolutions.jl#2]
How we should handle the truncation errors and type conversions is unclear. One idea is to use `Rational{BigInt}` whenever possible and document the API to encourage the user to pass the problem parameters as `Rational` types. 

@tanderson92 I am opening an issue so that we keep track of this and discuss ideas if needed.

**Comment by tanderson92** [comment]
We know that the code works as-is for numbers that are `Interval{Float64}`.

Would it suffice to check if we have either `Rational{BigInt}` or an `Interval{Float64}`? One wrinkle is that, unless there's some Julia feature for this of which I'm unaware, I do not think we can check if the type is an `Interval` without `using IntervalArithmetic`?

**Comment by maltezfaria** [comment]
I don't think we can check if the input type is an `Interval` without having the `Interval` package as a dependency, at least not in an easy way. Since as you pointed out the code works for very generic `Number` types, the fix is probably a documentation one: we explain that if you want to have bounds on the coefficients, or if you want them to be exact, you can use either an `Interval` or a `Rational` for the input parameters. Seems like a decent compromise. I will leave this open until we document the API.

**Comment by maltezfaria** [comment]
Fixed by documentation changes in 453e8e69af535a210e1a099d502c9286cd5f2720
